version: '3.8'

services:

  userservice:
    build: .
    container_name: userservice
    restart: always
    ports:
      - "9051:9051"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3356/dockerDBLab2?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: cisco1234
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - mynetwork


  db:
    image: mysql:8.0
    container_name: mysql55
    restart: always
    ports:
      - "3356:3356"
    environment:
      MYSQL_DATABASE: dockerDBLab2
      MYSQL_ROOT_PASSWORD: cisco1234
    command: --port=3356  # Указываем MySQL слушать 3356 внутри контейнера
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mynetwork

networks:
  mynetwork:
    external: true  # Подключаемся к уже существующей сети

volumes:
  mysql_data:
